language: ruby
cache: bundler
sudo: false
rvm:
  - 2.2
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  matrix:
  - "RAILS_VERSION=4.2.4"
notifications:
  email:
    recipients:
      - "ul-dlt-hydra@lists.psu.edu"
    on_success: "change"
    on_failure: "always"
  irc:
    channels:
      - "irc.freenode.org#scholarsphere"
      - "irc.freenode.org#projecthydra"
    template:
      - "%{repository}//%{branch}@%{commit} by %{author}: %{message} - %{build_url}"
before_script:
  - jdk_switcher use oraclejdk8
